/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./**/*.{html,razor,cshtml}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-container": "#7d8497",
        "on-secondary-container": "#596372",
        "surface-container-high": "#e8e8e8",
        "inverse-primary": "#c0c6db",
        "secondary-fixed": "#d9e3f4",
        "primary-fixed": "#dce2f7",
        "on-tertiary-fixed-variant": "#44474a",
        "on-error": "#ffffff",
        "on-tertiary-fixed": "#191c1f",
        "on-surface": "#1a1c1c",
        "surface-container-low": "#f3f3f4",
        "inverse-surface": "#2f3131",
        "primary-fixed-dim": "#c0c6db",
        "surface-container": "#eeeeee",
        "on-tertiary": "#ffffff",
        "outline": "#76777d",
        "error-container": "#ffdad6",
        "secondary-container": "#d6e0f1",
        "on-tertiary-container": "#818488",
        "outline-variant": "#c6c6cd",
        "on-primary": "#ffffff",
        "surface": "#f9f9f9",
        "surface-variant": "#e2e2e2",
        "surface-dim": "#dadada",
        "tertiary-fixed": "#e0e2e6",
        "tertiary-container": "#191c1f",
        "inverse-on-surface": "#f0f1f1",
        "on-background": "#1a1c1c",
        "primary-container": "#141b2b",
        "secondary-fixed-dim": "#bdc7d8",
        "on-secondary-fixed": "#121c28",
        "surface-tint": "#575e70",
        "secondary": "#555f6d",
        "on-primary-fixed": "#141b2b",
        "background": "#f9f9f9",
        "on-secondary": "#ffffff",
        "on-primary-fixed-variant": "#404758",
        "tertiary": "#000000",
        "surface-container-lowest": "#ffffff",
        "error": "#ba1a1a",
        "tertiary-fixed-dim": "#c4c7ca",
        "on-secondary-fixed-variant": "#3e4755",
        "on-surface-variant": "#45464c",
        "surface-bright": "#f9f9f9",
        "surface-container-highest": "#e2e2e2",
        "primary": "#000000",
        "on-error-container": "#93000a"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "space-xs": "0.25rem",
        "gutter-mobile": "1rem",
        "margin-mobile": "1rem",
        "margin": "2.5rem",
        "space-lg": "1.5rem",
        "gutter": "1.5rem",
        "space-md": "1rem",
        "space-sm": "0.5rem",
        "space-xl": "2.5rem"
      },
      fontFamily: {
        "display-hero-mobile": ["Inter"],
        "label-md": ["Inter"],
        "headline-sm": ["Inter"],
        "display-hero": ["Inter"],
        "headline-xl": ["Inter"],
        "headline-lg": ["Inter"],
        "body-sm": ["Inter"],
        "headline-xl-mobile": ["Inter"],
        "body-md": ["Inter"],
        "overline": ["Inter"],
        "label-sm": ["Inter"],
        "body-lg": ["Inter"],
        "headline-md": ["Inter"]
      },
      fontSize: {
        "display-hero-mobile": ["36px", { "lineHeight": "44px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "label-md": ["14px", { "lineHeight": "20px", "letterSpacing": "-0.005em", "fontWeight": "500" }],
        "headline-sm": ["18px", { "lineHeight": "26px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "display-hero": ["56px", { "lineHeight": "64px", "letterSpacing": "-0.03em", "fontWeight": "600" }],
        "headline-xl": ["40px", { "lineHeight": "48px", "letterSpacing": "-0.025em", "fontWeight": "600" }],
        "headline-lg": ["30px", { "lineHeight": "38px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "body-sm": ["13px", { "lineHeight": "18px", "letterSpacing": "0.005em", "fontWeight": "400" }],
        "headline-xl-mobile": ["28px", { "lineHeight": "36px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "body-md": ["14px", { "lineHeight": "22px", "letterSpacing": "0em", "fontWeight": "400" }],
        "overline": ["11px", { "lineHeight": "16px", "letterSpacing": "0.08em", "fontWeight": "600" }],
        "label-sm": ["12px", { "lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "500" }],
        "body-lg": ["16px", { "lineHeight": "26px", "letterSpacing": "-0.005em", "fontWeight": "400" }],
        "headline-md": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.015em", "fontWeight": "600" }]
      }
    }
  }
}
